name: Test
on:
  - workflow_dispatch
  - push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.9.1
      - name: Install
        run: "npm i"
      - name: Install
        run: "npm run test"
